
###

GET https://ismp2.knia.or.kr/carins/resCompare.knia  HTTP/1.1

special3Yn=0
&special1Opt=00000
&special2Opt3=000
&reqFlow=M
&insAge=0
&insCarName=%EB%AA%A8%EB%8B%9D
&lawViolCode=C012
&past1AcdtCnt=
&special9Yn=0
&agreeYn=Y
&special3Opt=00000000
&driverScope=3
&tng1Amt=20000
&special4Yn=0
&special5Yn=0
&carUseType=1
&past1AcdtPoint=
&psn2Amt=00000
&carPlateNo=000000000000
&carPlateAgentCode=1
&special6Yn=0
&minBrith=19901125
&agreeDate=20190925
&agreeType=5
&orgcd=
&special8Yn=0
&driverInjAmt=1500
&otherCarYn=1
&myPayRatio=20
&special7Yn=0
&acdt2yrCnt=
&psn2Yn=1
&ownManyCarCode=0
&emgServiceYn=1
&noInsYn=1
&resultType=json
&insTypeCode=
&special6Opt=000
&special5Opt=000
&discExtraGrade=11Z
&insHis=0
&insExpireDate=
&acdt1yrCnt=
&insResellerType=
&contInfoSeq=0004
&insCarMadeYm=2011
&driverDthAmt=3000
&tngBaseAmt=200
&kniaSsn=9011251M00001
&insCarrerCode=0
&carInfoSeq=0025
&mycarYn=1
&authType=5
&acdt3yrCnt=
&rgstGubun=1
&multiChargeYn=
&carPlateGubun=0
&insCarNameCodeType=1
&insCarNameCode=11G24
&special7Opt1=00000
&yyyyMMdd=20190925
&special7Opt2=00000
&driverInjGubun=1
&insContNo=
&special2Yn=0
&special1Yn=0
&insTerm=2019092520200925
&past3AcdtCnt=
&specExtraCode=

###

GET https://ismp2.knia.or.kr/carins/resCompare.knia HTTP/1.1

reqFlow=M
&ansCd=000
&carPlateNo=000000000000
&carPlateGubun=0
&resultType=json
&carPlateAgentCode=1
&carInfoSeq=0025
&contInfoSeq=0005
&kniaSsn=9011251M00001
